# syntax=docker/dockerfile:1

##
## Build
##
FROM golang:1.17-alpine AS build

WORKDIR /app

COPY go.mod ./
COPY go.sum ./
# Download necessary Go modules
RUN go mod download

COPY emqx-auth-http/*.go ./

RUN go build -o /emqx-auth-http

##
## Deploy
##
FROM alpine:3.10

WORKDIR /

COPY --from=build /emqx-auth-http /emqx-auth-http

EXPOSE 8080

ENTRYPOINT ["/emqx-auth-http"]